//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticCodeAnalysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticCodeAnalysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare a const string variable instead of using hardcoded literals.
        /// </summary>
        internal static string LiteralRuleDescription {
            get {
                return ResourceManager.GetString("LiteralRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal &apos;{0}&apos; should be extracted into a const variable.
        /// </summary>
        internal static string LiteralRuleFormat {
            get {
                return ResourceManager.GetString("LiteralRuleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use constants instead of hardcoded literals.
        /// </summary>
        internal static string LiteralRuleTitle {
            get {
                return ResourceManager.GetString("LiteralRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private readonly fields are prefixed with an underscore.
        /// </summary>
        internal static string ReadonlyFieldRuleDescription {
            get {
                return ResourceManager.GetString("ReadonlyFieldRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is private and readonly, but does not start with an underscore and lowercase letter.
        /// </summary>
        internal static string ReadonlyFieldRuleFormat {
            get {
                return ResourceManager.GetString("ReadonlyFieldRuleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private readonly fields are prefixed with an underscore.
        /// </summary>
        internal static string ReadonlyFieldTitle {
            get {
                return ResourceManager.GetString("ReadonlyFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braces are required for if and while statements if they do not exit execution immediately.
        /// </summary>
        internal static string RequiredBracesRuleDescription {
            get {
                return ResourceManager.GetString("RequiredBracesRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brace &apos;{&apos; expected for single line conditional since it does not exit immediately.
        /// </summary>
        internal static string RequiredBracesRuleFormat {
            get {
                return ResourceManager.GetString("RequiredBracesRuleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braces required for non-exiting code.
        /// </summary>
        internal static string RequiredBracesRuleTitle {
            get {
                return ResourceManager.GetString("RequiredBracesRuleTitle", resourceCulture);
            }
        }
    }
}
